### ManualRecodePlayerIdWebscrappe

import pandas as pd
import numpy as np

def manual_recode_id_webscrapping(list_players):
    # list_players['Name'] =  np.where(list_players['Name']=="James Michael","James Michael McAdoo",list_players['Name'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Walt Williams","w/williwa02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Alton Ford","f/fordal02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Cherokee Parks","p/parksch02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Rod Strickland","s/stricro02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Nick Van","v/vanexni01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Keith Van","v/vanhoke01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="James Thomas","t/thomaja02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="John Thomas","t/thomajo02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Donta Smith","s/smithdo04/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Corliss Williamson","w/willico02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Clifford Robinson","r/robincl02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Bracey Wright","w/wrighbr02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Alvin Williams","w/willial02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Dajuan Wagner","w/wagneda02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Kevin Willis","w/willike02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Marcus Vinicius","v/vincima01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Antoine Walker","w/walkean02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Juan Carlos","n/navarju01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Bobby Jones","j/jonesbo02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Mouhamed Sene","s/senesa01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Lorenzen Wright","w/wrighlo02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Wally Szczerbiak","s/szczewa02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Anthony Roberson","r/roberan02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Alando Tucker","t/tuckeal02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Didier IlungaMbenga","m/mbengdj01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="David Andersen","a/anderda03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Mario West","w/westma02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Joe Smith","s/smithjo02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jason Collier","c/collija02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jarron Collins","c/collija03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jermaine Taylor","t/tayloje02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jay Williams","w/willija03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jason Williams","w/willija02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jawad Williams","w/willija04/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Antonio Lang","l/langan02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Brevin Knight","k/knighbr01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Gerard King","k/kingge02/",list_players['id_webscrapping'])
    # list_players['id_webscrapping'] =  np.where(list_players['Name']=="Chris Johnson" & list_players['Pos=="C" ,"j/johnsch03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Mark Jones","j/jonesma03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Eddie Jones","j/jonesed02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Dwayne Jones","j/jonesdw02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Charles Jones","j/jonesch03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Ken Johnson","j/johnske03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Larry Johnson","j/johnsla02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Ervin Johnson","j/johnser02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="DerMarr Johnson","j/johnsde03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="DeMarco Johnson","j/johnsde02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Anthony Johnson","j/johnsan02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Marc Jackson","j/jacksma02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Luke Jackson","j/jackslu02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Cedric Henderson","h/hendece02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Shelden Williams","w/willish02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Todd Fuller","f/fulleto02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Patrick Ewing","e/ewingpa02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Chris Dudley","d/dudlech02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jordan Williams","w/willijo03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Mark Davis","d/davisma02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Armon Johnson","j/johnsar02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Mitchell Butler","b/butlemi02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Randy Brown","b/brownra02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Antonio Anderson","a/anderan02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Courtney Alexander","a/alexaco02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Josh Davis","d/davisjo02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Keith Benson","b/bensoke02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Walker Russell","r/russewa02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Mychel Thompson","t/thompmy02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Devin Brown","b/brownde02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Dee Brown","b/brownde03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Derrick Brown","b/brownde04/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Sasha Pavlovic","p/pavloal01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Damien Wilkins","w/wilkida02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="James White","w/whiteja02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Dominique Jones","j/jonesdo02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Daequan Cook","c/cookda02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Martell Webster","w/webstma02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Diante Garrett","g/garredi02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Nando De","d/decolna01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Rodney White","w/whitero02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Royce White","w/whitero03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Darius JohnsonOdom","j/johnsda03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Chris Smith","s/smithch05/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Rashard Lewis","l/lewisra02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Ray Allen","a/allenra02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Stephen Jackson","j/jacksst02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Tony Mitchell","m/mitchto02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Ronnie Brewer","b/brewero02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jason Collins","c/collija04/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Glen Rice","r/ricegl01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Larry Drew","d/drewla02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Henry Walker","w/walkebi01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Shawne Williams","w/willish03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jeffery Taylor","t/tayloje03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Chris Johnson","j/johnsch04/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jerian Grant","g/grantje02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jordan Hamilton","h/hamiljo02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Greg Smith","s/smithgr02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Andre Miller","m/millean02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Kevin Martin","m/martike02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jeff Ayres","p/pendeje02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Josh Smith","s/smithjo03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jason Thompson","t/thompja02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Mo Williams","w/willima01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="PJ Hairston","h/hairspj02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Sheldon Mac","m/mcclesh01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="David Lee","l/leeda02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Gerald Henderson","h/hendege02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Reggie Williams","w/willire02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="John Lucas","l/lucasjo02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Willie Reed","r/reedwi02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Brandan Wright","w/wrighbr03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Metta World","a/artesro01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Brice Johnson","j/johnsbr02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Bobby Brown","b/brownbo02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="James Michael McAdoo","m/mcadoja01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Matt Barnes","b/barnema02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="James Jones","j/jonesja02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Dahntay Jones","j/jonesda02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Bojan Bogdanovic","b/bogdabo02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Derrick Williams","w/willide02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Edy Tavares","t/tavarwa01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Mike Dunleavy","d/dunlemi02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Taurean Prince","p/princta02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Isaiah Thomas","t/thomais02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Damion Lee","l/leeda03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Marcus Morris","m/morrima03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Markieff Morris","m/morrima02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jaylen Brown","b/brownja02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jabari Bird","b/birdja01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Kemba Walker","w/walkeke02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Marvin Williams","w/willima02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Larry Nance","n/nancela02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jeff Green","g/greenje02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Cedi Osman","o/osmande01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="John Holland","h/hollajo02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Wesley Matthews","m/matthwe02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Harrison Barnes","b/barneha02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Dennis Smith","s/smithde03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jalen Jones","j/jonesja04/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="JJ Barea","b/bareajo01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Maxi Kleber","k/klebima01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Stanley Johnson","j/johnsst04/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Damian Jones","j/jonesda03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Clint Capela","c/capelca01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Nene NA","h/hilarne01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Markel Brown","b/brownma02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Joe Johnson","j/johnsjo02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Luc Mbah","m/mbahalu01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Glenn Robinson","r/robingl01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Tobias Harris","h/harrito02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Lou Williams","w/willilo02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Gary Payton","p/paytoga01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Derrick Jones","j/jonesde02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Sterling Brown","b/brownst02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Xavier Munford","m/munfoxa02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Marshall Plumlee","p/plumlma02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Anthony Brown","b/brownan02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Anthony Davis","d/davisan02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jordan Crawford","c/crawfjo02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Tim Hardaway","h/hardati02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Troy Williams","w/willitr02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Frank Ntilikina","n/ntilila01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Andre Roberson","r/roberan03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Dakari Johnson","j/johnsda04/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Daniel Hamilton","h/hamilda02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jonathon Simmons","s/simmojo02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Brandon Knight","k/knighbr03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Josh Jackson","j/jacksjo02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Alan Williams","w/willial03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="JaKarr Sampson","s/sampsja02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Danny Green","g/greenda02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Patty Mills","m/millspa02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jason Smith","s/smithja02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Charlie Brown","b/brownch02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Robert Williams","w/williro04/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Caleb Martin","m/martica02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Cristiano Felício","m/feliccr01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Louis King","k/kinglo02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Alize Johnson","j/johnsal02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Kevin Porter","p/porteke02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Ante Zizic","z/zizican01/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Josh Reaves","r/reavejo02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Brian Bowen","b/bowenbr02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jaren Jackson","j/jacksja02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Kelan Martin","m/martike03/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jacob Evans","e/evansja02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Jaxson Hayes","h/hayesja02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Kenrich Williams","w/willike04/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Deonte Burton","b/burtode02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Johnathan Williams","w/willijo04/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Matt Thomas","t/thomama02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Glenn Robinson","r/robingl02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Cameron Johnson","j/johnsca02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Gary Trent","t/trentga02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Keldon Johnson","j/johnske04/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Terence Davis","d/daviste02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Justin WrightForeman","w/wrighju02/",list_players['id_webscrapping'])
    list_players['id_webscrapping'] =  np.where(list_players['Name']=="Miles Bridges","b/bridgmi02/",list_players['id_webscrapping'])

    return list_players

    #######

    # 324	James Robinson	r/robinja01
    # 484	Mike Smith	s/smithmi01
    # 780	Donny Marshall	m/marshdo01
    # 3329	Steven Smith	s/smithst01
    # 5577	JaJuan Johnson	j/johnsja01
    # 5754	Trey Thompkins	t/thomptr01
    # 8681	Derrick Jones Jr.	j/jonesde01
    # 9123	Matt Williams	w/willima01
    # 9771	Dairis Bertans	b/bertada01
    # 10019	Charlie Brown Jr.	b/brownch01
    # 10043	Javonte Green	g/greenja01
    # 10586	Justin Wright-Foreman	w/wrighju01
    # 10833	Kenyon Martin Jr.	m/martike01
    # 10977	Jaden McDaniels	m/mcdanja01
    # 11115	Jalen Smith	s/smithja01
    # 11238	Chaundee Brown Jr.	b/brownch01
    # 11249	Jalen Johnson	j/johnsja01
    # 11298	Kessler Edwards	e/edwarke01
    # 11478	Jalen Green	g/greenja01
    # 11589	Ziaire Williams	w/willizi01
    # 11675	Trey Murphy III	m/murphtr01
    # 11723	Jeremiah Robinson-Earl	r/robinje01
    # 11888	David Johnson	j/johnsda01
    # 11902	Jared Butler	b/butleja01