vars:
  - project:
      directory: .
stages:
  gamelog_data_acquisition:
    cmd: python3 -m src.exctract.gamelog_data_acquisition --config=params.yaml
    deps:
      - src/exctract/gamelog_data_acquisition.py
    params:
      - base
      - gamelog_data_acquisition
    # outs:
    #   - pipeline_output/gamelog/
  schedule_data_acquisition:
    cmd: python3 -m src.exctract.schedule_data_acquisition --config=params.yaml
    deps:
      - src/exctract/schedule_data_acquisition.py
    params:
      - base
      - schedule_data_acquisition
  player_attributes_data_acquisition:
    cmd: python3 -m src.exctract.player_attributes_data_acquisition --config=params.yaml
    deps:
      - src/exctract/player_attributes_data_acquisition.py
    params:
      - base
      - player_attributes_data_acquisition
  player_salary_data_acquisition:
    cmd: 
    - python3 -m src.exctract.player_salary_data_acquisition  --config=params.yaml
    deps:
      - src/exctract/player_salary_data_acquisition.py
    params:
      - base
      - player_salary_data_acquisition
  gamelog_schedule_unification:
    cmd: 
    - >- 
      python3 -m src.transform.gamelog_schedule_unification 
      --gamelog-data-path ${project.directory}/${gamelog_data_acquisition.output_folder}
      --gamelog-name-pattern ${gamelog_data_acquisition.data_type}
      --schedule-data-path ${project.directory}/${schedule_data_acquisition.output_folder}
      --schedule-name-pattern ${schedule_data_acquisition.data_type}
      --unified-file-path ${project.directory}/${gamelog_schedule_unification.data_path}
      --unified-file-name ${gamelog_schedule_unification.file_name}
    deps:
      - src/transform/gamelog_schedule_unification.py
    params:
      - base
      - gamelog_schedule_unification
  player_attributes_salaries_unification:
    cmd: 
    - >- 
      python3 -m src.transform.player_attributes_salaries_unification
      --schedule-data-path ${project.directory}/${schedule_data_acquisition.output_folder}
      --schedule-name-pattern ${schedule_data_acquisition.data_type}
      --players-attributes-data-path ${project.directory}/${player_attributes_data_acquisition.output_folder}
      --players-attributes-name-pattern ${player_attributes_data_acquisition.data_type}
      --players-salary-data-path ${project.directory}/${player_salary_data_acquisition.output_folder}
      --players-salary-name-pattern ${player_salary_data_acquisition.data_type}
      --output-dest-file-path ${project.directory}/${player_attributes_salaries_unification.data_path}
      --output-dest-file-name ${player_attributes_salaries_unification.file_name}
    
    deps:
      - src/transform/player_attributes_salaries_unification.py
    params:
      - base
      - player_attributes_salaries_unification
    # outs:
    #   - pipeline_output/schedule/
  # writte_final_output_to_s3:
  #   cmd:
  #     - >-
  #       aws s3 cp 
  #       ./data_pipeline/final/
  #       s3://cad-yannick/syncropshield-data-pipeline-output/datasets/ --profile=cads-it --recursive
  #     - >-
  #       aws s3 cp 
  #       ./reports/eda/
  #       s3://cad-yannick/syncropshield-data-pipeline-output/eda_report/ --profile=cads-it --recursive
  #   deps:
  #     - data_pipeline/final/
  #     - reports/eda/


