#dvc repro linear/dvc.yaml
vars:
  - project:
      directory: .
stages:
  gamelog_data_acquisition:
    foreach: ${global_params.season}
    do:
      cmd: 
      - >- 
        python3 -m src.exctract.gamelog_data_acquisition 
        --data-type ${gamelog_data_acquisition.data_type}
        --season ${item}
        --team ${gamelog_data_acquisition.team}
        --output-folder ${project.directory}/${gamelog_data_acquisition.output_folder}
      deps:
        - src/exctract/gamelog_data_acquisition.py
      params:
        - base
        - gamelog_data_acquisition
      outs:
        - ${project.directory}/${gamelog_data_acquisition.output_folder}/${gamelog_data_acquisition.data_type}_${item}_${gamelog_data_acquisition.team}.csv
  schedule_data_acquisition:
    foreach: ${global_params.season}
    do:
      cmd:
      - >- 
        python3 -m src.exctract.schedule_data_acquisition 
        --data-type ${schedule_data_acquisition.data_type}
        --season ${item}
        --team ${schedule_data_acquisition.team}
        --output-folder ${project.directory}/${schedule_data_acquisition.output_folder}
      deps:
        - src/exctract/schedule_data_acquisition.py
      params:
        - base
        - schedule_data_acquisition
      outs:
        - ${project.directory}/${schedule_data_acquisition.output_folder}/${schedule_data_acquisition.data_type}_${item}_${schedule_data_acquisition.team}.csv
  gamelog_cleaning_and_transformation:
    foreach: ${global_params.season}
    do:
      cmd:
      - >- 
        python3 -m src.transform.gamelog_cleaning_and_transformation 
        --file-name ${gamelog_data_acquisition.data_type}_${item}_${gamelog_data_acquisition.team}
        --input-folder ${project.directory}/${gamelog_data_acquisition.output_folder}
        --output-folder ${project.directory}/${gamelog_cleaning_and_transformation.output_folder}
      deps:
        - src/transform/gamelog_cleaning_and_transformation.py
        - ${project.directory}/${gamelog_data_acquisition.output_folder}/${gamelog_data_acquisition.data_type}_${item}_${gamelog_data_acquisition.team}.csv
      params:
        - base
        - gamelog_data_acquisition
        - gamelog_cleaning_and_transformation
      outs:
        - ${project.directory}/${gamelog_cleaning_and_transformation.output_folder}/${gamelog_data_acquisition.data_type}_${item}_${gamelog_data_acquisition.team}.csv
  schedule_cleaning_and_transformation:
    foreach: ${global_params.season}
    do:
      cmd:
      - >- 
        python3 -m src.transform.schedule_cleaning_and_transformation 
        --file-name ${schedule_data_acquisition.data_type}_${item}_${schedule_data_acquisition.team}
        --input-folder ${project.directory}/${schedule_data_acquisition.output_folder}
        --output-folder ${project.directory}/${schedule_cleaning_and_transformation.output_folder}
      deps:
        - src/transform/schedule_cleaning_and_transformation.py
        - ${project.directory}/${schedule_data_acquisition.output_folder}/${schedule_data_acquisition.data_type}_${item}_${gamelog_data_acquisition.team}.csv
      params:
        - base
        - schedule_data_acquisition
        - schedule_cleaning_and_transformation
      outs:
        - ${project.directory}/${schedule_cleaning_and_transformation.output_folder}/${schedule_data_acquisition.data_type}_${item}_${schedule_data_acquisition.team}.csv
  writte_final_output_to_s3:
    foreach: ${global_params.season}
    do:
      cmd:
      - >-
        aws s3 cp 
        ${project.directory}/${gamelog_cleaning_and_transformation.output_folder}/${gamelog_data_acquisition.data_type}_${item}_${gamelog_data_acquisition.team}.csv
        s3://foreshadownba/data-engineering-pipeline-output/gamelogs/ --profile=ipfy
      - >-
        aws s3 cp 
        ${project.directory}/${schedule_cleaning_and_transformation.output_folder}/${schedule_data_acquisition.data_type}_${item}_${schedule_data_acquisition.team}.csv
        s3://foreshadownba/data-engineering-pipeline-output/schedules/ --profile=ipfy
      deps:
      - ${project.directory}/${schedule_cleaning_and_transformation.output_folder}/${schedule_data_acquisition.data_type}_${item}_${schedule_data_acquisition.team}.csv
      - ${project.directory}/${gamelog_cleaning_and_transformation.output_folder}/${gamelog_data_acquisition.data_type}_${item}_${gamelog_data_acquisition.team}.csv



