base:
  log_level: INFO

global_params:
  season:
  - 2025

gamelog_data_acquisition:
  team: all
  data_type: gamelog
  output_folder: pipeline_output/gamelog/

schedule_data_acquisition:
  team: all
  data_type: schedule
  output_folder: pipeline_output/schedule/

gamelog_cleaning_and_transformation:
  output_folder: pipeline_output/gamelog_cleaned/

schedule_cleaning_and_transformation:
  output_folder: pipeline_output/schedule_cleaned/

player_attributes_data_acquisition:
  team: all
  data_type: player_attributes
  output_folder: pipeline_output/player_attributes/

player_salary_data_acquisition:
  data_type: player_salary
  output_folder: pipeline_output/player_salary/

gamelog_schedule_unification:
  data_path: pipeline_output/unified
  file_name: nba_gamelog_schedule_dataset

player_attributes_salaries_unification:
  data_path: pipeline_output/unified
  file_name: player_attributes_salaries_dataset

load_gamelog_schedule_unified_to_csv:
  data_path: pipeline_output/final
  file_name: nba_gamelog_schedule_dataset

load_player_attributes_salaries_unified_to_csv:
  data_path: pipeline_output/final
  file_name: player_attributes_salaries_dataset
